# Generated by Django 4.0.4 on 2022-05-23 21:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('acti_title', models.CharField(max_length=200)),
                ('acti_date', models.CharField(max_length=100)),
                ('acti_insert', models.TextField()),
                ('acti_image', models.ImageField(blank=True, null=True, upload_to='activities/')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
