# Generated by Django 4.0.4 on 2022-05-17 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('acti_title', models.CharField(max_length=200)),
                ('acti_date', models.CharField(max_length=100)),
                ('acti_insert', models.TextField()),
                ('acti_image', models.ImageField(blank=True, null=True, upload_to='activities/')),
            ],
        ),
    ]
